# Remote theme directory
remote_theme: analytics-link/analytics-link.github.io

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

#-------------------------------
# General Site Settings
title: Stephen Nsoyuka JR
description: "Hi I'm Stephen, and I'm a Risk Analyst.  This portfolio captures the early phase of my data analytics journey, featuring mini-projects completed while building my technical skills. While most aren't risk-specific yet, my goal is to apply this growing expertise to real-world risk management challenges across areas like operational, credit, fraud, and sustainability risks. Feel free to explore my work - and visit my GitHub, LinkedIn, or download my CV using the links below!"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Risk Analytics <span style="color:#f58506"> Portfolio </span>
location: "Glasgow, UK"
resume_url: /docs/nsoyuka_cv.doc
avatar_image: /img/steve_pic.jpg

#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/stephennsoyukajr/" # Add your linkedln handle
github: "https://github.com/Stevonjr"  # Add your github handle

paginate: 6
paginate_path: "/page/:num"

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      read_time: true
      share: false


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

